Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import seaborn as sb

df = pd.DataFrame({'HÃ¸yde': 
                   [173, 178, 153, 175, 167, 155, 161, 164, 177, 157, 162, 165, 172, 165, 170, 167, 185, 170, 178, 185, 175, 183, 182],
                   'Skonummer': 
                   [42, 45, 37, 39, 40, 37, 39, 38, 40, 36, 38, 38, 40, 39, 39, 39, 42, 40, 43, 43, 43, 45, 43]})
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-c13a4dfdba01>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mseaborn[0m [0;32mas[0m [0msb[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m df = pd.DataFrame({'HÃ¸yde': 
[1;32m      5[0m                    [0;34m[[0m[0;36m173[0m[0;34m,[0m [0;36m178[0m[0;34m,[0m [0;36m153[0m[0;34m,[0m [0;36m175[0m[0;34m,[0m [0;36m167[0m[0;34m,[0m [0;36m155[0m[0;34m,[0m [0;36m161[0m[0;34m,[0m [0;36m164[0m[0;34m,[0m [0;36m177[0m[0;34m,[0m [0;36m157[0m[0;34m,[0m [0;36m162[0m[0;34m,[0m [0;36m165[0m[0;34m,[0m [0;36m172[0m[0;34m,[0m [0;36m165[0m[0;34m,[0m [0;36m170[0m[0;34m,[0m [0;36m167[0m[0;34m,[0m [0;36m185[0m[0;34m,[0m [0;36m170[0m[0;34m,[0m [0;36m178[0m[0;34m,[0m [0;36m185[0m[0;34m,[0m [0;36m175[0m[0;34m,[0m [0;36m183[0m[0;34m,[0m [0;36m182[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

